apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
  labels:
    app: serverless-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ray-head
  template:
    metadata:
      labels:
        app: serverless-llm
        component: ray-head
    spec:
      containers:
        - name: ray-head
          image: rayproject/ray-ml:2.10.0-py310
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
            - containerPort: 8265
          args:
            - "ray"
            - "start"
            - "--head"
            - "--num-cpus=8"
            - "--dashboard-host=0.0.0.0"
          env:
            - name: RAY_GRAFANA_HOST
              value: "prometheus"
          resources:
            limits:
              cpu: "8"
              memory: "16Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
  labels:
    app: serverless-llm
spec:
  selector:
    component: ray-head
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
    - protocol: TCP
      port: 8265
      targetPort: 8265
